- name: install nginx
  apt: name=nginx state=present

- name: copy across new virtual host
  template:
    src=nginx-site-default.j2
    dest=/etc/nginx/sites-available/vagrant
  notify:
    - reload-nginx

- name: remove default virtual host
  file:
    path=/etc/nginx/sites-enabled/default
    state=absent
  notify:
    - reload-nginx

- name: enable new vagrant virtual host
  file:
    src=/etc/nginx/sites-available/vagrant
    dest=/etc/nginx/sites-enabled/vagrant
    state=link
  notify:
    - reload-nginx