- name: add php7.0 package
  apt_repository: repo='ppa:ondrej/php'

- name: install php7
  apt: name={{ item }} state=present update_cache=yes
  with_items:
     - php7.0
     - php7.0-fpm
     - php7.0-intl
     - php7.0-mysql
     - php7.0-dev

- name: copy across new php config
  template:
    src=php7-fpm-php.ini.j2
    dest=/etc/php/7.0/fpm/php.ini
  notify:
    - reload-php7-fpm
