# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    security.authentication.success_handler:
        class: AppBundle\Security\Authentication\AuthenticationHandler
        arguments: ['@doctrine.orm.entity_manager', '@security.http_utils', {}]
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    app.slugger:
        class: AppBundle\Utils\Slugger

    user.service:
        class: AppBundle\Service\UserService
        arguments: ['@user.repository', '@security.password_encoder', '@app.slugger']

    user.repository:
        class: AppBundle\Repository\UserRepository
        arguments: [AppBundle\Entity\User]
        factory: ["@doctrine.orm.entity_manager", getRepository]
