homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }

user_registration:
    path: /register
    defaults: { _controller: AppBundle:Registration:register }

login_route:
    path: /login
    defaults: { _controller: AppBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout
