homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }

user_registration:
    path: /register
    defaults: { _controller: AppBundle:Registration:register }

user_overview:
    path: /user
    defaults: { _controller: AppBundle:User:index }

user_profile:
    path: /user/{slug}
    defaults: { _controller: AppBundle:User:profile }

user_edit:
    path: /user/{slug}/edit
    defaults: { _controller: AppBundle:User:edit }

mail_inbox:
    path: /mail/inbox
    defaults: { _controller: AppBundle:Mail:inbox }

mail_outbox:
    path: /mail/outbox
    defaults: { _controller: AppBundle:Mail:outbox }

mail_archive:
    path: /mail/archive
    defaults: { _controller: AppBundle:Mail:archive }

mail_detail:
    path: /mail/show/{id}
    defaults: { _controller: AppBundle:Mail:show }

mail_new:
    path: /mail/new
    defaults: { _controller: AppBundle:Mail:create }

mail_reply:
    path: /mail/reply/{id}
    defaults: { _controller: AppBundle:Mail:reply }

login_route:
    path: /login
    defaults: { _controller: AppBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout
